# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos: Pedro Martinez <br>
Url: https://github.com/.../03MAIR---Algoritmos-de-Optimizacion---2019/tree/master/SEMINARIO<br>
Problema: Organizar sesiones de doblaje.


Descripción del problema:

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio
de grabación independientemente del número de tomas que se graben. No es posible grabar
más de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que se gasto
por los servicios de los actores de doblaje sea el menor posible. Los datos son:


- numero de actores: 10
- numero de tomas: 30


                                        

| Actor | 1  | 2  | 3  | 4  | 5  | 6 | 7 | 8 | 9 | 10 |   |       |
|-------|----|----|----|----|----|---|---|---|---|----|---|-------|
| Toma  |    |    |    |    |    |   |   |   |   |    |   | Total |
| 1     | 1  | 1  | 1  | 1  | 1  | 0 | 0 | 0 | 0 | 0  |   | 5     |
| 2     | 0  | 0  | 1  | 1  | 1  | 0 | 0 | 0 | 0 | 0  |   | 3     |
| 3     | 0  | 1  | 0  | 0  | 1  | 0 | 1 | 0 | 0 | 0  |   | 3     |
| 4     | 1  | 1  | 0  | 0  | 0  | 0 | 1 | 1 | 0 | 0  |   | 4     |
| 5     | 0  | 1  | 0  | 1  | 0  | 0 | 0 | 1 | 0 | 0  |   | 3     |
| 6     | 1  | 1  | 0  | 1  | 1  | 0 | 0 | 0 | 0 | 0  |   | 4     |
| 7     | 1  | 1  | 0  | 1  | 1  | 0 | 0 | 0 | 0 | 0  |   | 4     |
| 8     | 1  | 1  | 0  | 0  | 0  | 1 | 0 | 0 | 0 | 0  |   | 3     |
| 9     | 1  | 1  | 0  | 1  | 0  | 0 | 0 | 0 | 0 | 0  |   | 3     |
| 10    | 1  | 1  | 0  | 0  | 0  | 1 | 0 | 0 | 1 | 0  |   | 4     |
| 11    | 1  | 1  | 1  | 0  | 1  | 0 | 0 | 1 | 0 | 0  |   | 5     |
| 12    | 1  | 1  | 1  | 1  | 0  | 1 | 0 | 0 | 0 | 0  |   | 5     |
| 13    | 1  | 0  | 0  | 1  | 1  | 0 | 0 | 0 | 0 | 0  |   | 3     |
| 14    | 1  | 0  | 1  | 0  | 0  | 1 | 0 | 0 | 0 | 0  |   | 3     |
| 15    | 1  | 1  | 0  | 0  | 0  | 0 | 1 | 0 | 0 | 0  |   | 3     |
| 16    | 0  | 0  | 0  | 1  | 0  | 0 | 0 | 0 | 0 | 1  |   | 2     |
| 17    | 1  | 0  | 1  | 0  | 0  | 0 | 0 | 0 | 0 | 0  |   | 2     |
| 18    | 0  | 0  | 1  | 0  | 0  | 1 | 0 | 0 | 0 | 0  |   | 2     |
| 19    | 1  | 0  | 1  | 0  | 0  | 0 | 0 | 0 | 0 | 0  |   | 2     |
| 20    | 1  | 0  | 1  | 1  | 1  | 0 | 0 | 0 | 0 | 0  |   | 4     |
| 21    | 0  | 0  | 0  | 0  | 0  | 1 | 0 | 1 | 0 | 0  |   | 2     |
| 22    | 1  | 1  | 1  | 1  | 0  | 0 | 0 | 0 | 0 | 0  |   | 4     |
| 23    | 1  | 0  | 1  | 0  | 0  | 0 | 0 | 0 | 0 | 0  |   | 2     |
| 24    | 0  | 0  | 1  | 0  | 0  | 1 | 0 | 0 | 0 | 0  |   | 2     |
| 25    | 1  | 1  | 0  | 1  | 0  | 0 | 0 | 0 | 0 | 1  |   | 4     |
| 26    | 1  | 0  | 1  | 0  | 1  | 0 | 0 | 0 | 1 | 0  |   | 4     |
| 27    | 0  | 0  | 0  | 1  | 1  | 0 | 0 | 0 | 0 | 0  |   | 2     |
| 28    | 1  | 0  | 0  | 1  | 0  | 0 | 0 | 0 | 0 | 0  |   | 2     |
| 29    | 1  | 0  | 0  | 0  | 1  | 1 | 0 | 0 | 0 | 0  |   | 3     |
| 30    | 1  | 0  | 0  | 1  | 0  | 0 | 0 | 0 | 0 | 0  |   | 2     |
|       |    |    |    |    |    |   |   |   |   |    |   |       |
| TOTAL | 22 | 14 | 13 | 15 | 11 | 8 | 3 | 4 | 2 | 2  |   |       |


In [1]:
import numpy as np

doblaje = np.genfromtxt('doblaje.csv', delimiter=',')
print(doblaje)

[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 1. 0. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 0. 1. 0.]
 [1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


## Estudio del espacio de soluciones.


(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>
¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.


Si no tenemos en cuenta que el numero de escenas maximo por día es 6, para contar el numero de organizaciones diferentes tenemos que tener en cuenta tres simetrias que contiene el problema:

- El orden de los dias no es relevante y hace indistinguibles dos repartos de escenas que solo se distingan en una permutación de los dias:
    ej.  dia 1 = (1,2,3), dia 2 = (4,5,6) es el mismo escenario que dia 1 = (4,5,6) dia 2 = (1,2,3)
- El orden de las escenas de en un mismo dia es irrelevante:
    ej. (1,2,3)=(2,3,1)
- Hay elementos similates como en nuestro caso son las escenas 6-7; 17-19-23; 28-30, esto hace indistinguible dos repartos de la forma:

    ej. (1,2,28)=(1,2,30)
  
  Esta simetria esta mas relacionada con estos datos en particular que con la estructura combinatoria del problema, por ello la tendremos en cuenta en la funcion para optimizar por fuerza bruta, pero no para el estudio combinatorio del problema.

En terminos combinatios podemos reformular el problema como:

Sea $\chi$ un conjunto de n elementos distinguibles {1,2,3,4...n} (en nuesto caso n=30 escenas) y A una colección de subconjuntos {$A_1,A_2,...A_k$} (en nuesto caso A_i es el i-esimo día) de $\chi$ tal que:

- forman una partición de $\chi$ es decir $\chi =\bigcup^k_{i=1}A_i$ y $A_i \cap A_j = \emptyset  $

- ningun A_i es un conjunto vacio (no tiene  sentido un dia sin escenas).

esta estrucutura se llama una partición de $\chi$ en k bloques no vacios. Como vemos el orden de los bolques es irrelebante y el orden de cada elemento en cada subconjunto tampoco es importante.

Como un ejemplo podemos mostrar el numero de particiones del conjunto (1,2,3)

$$\chi=(1,2,3) \rightarrow  (1,2,3)\wr(1,2)\cup(3)\wr(1,3)\cup(2)\wr(2,3)\cup(1)\wr(1)\cup(2)\cup(3)$$


Esbozamos nuestra forma de contar el nuemero de soluciones:

1. Calculamos los  tamaños de los subconjuntos, esto es las formas que hay de distribuir 30 elementos en subconjuntos, en nuestro ejemplo anterior las formas de distribuir 3 elementos en subconjuntos son: un subconjunto de 3 elementos, un subconjunto con 1 y otro con 2 y por ultimo 3 subconjuntos de un elemento llamaremos a cada una de estas distribuciones un horario. Es facil ver que las formas de distribuir n elementos en subconjuntos sin dejar ningun subconjunto vacio son las formas que hay de sumar n, en combinatoria conocemos esto como un particion de un numero. Para este paso usaremos una versión del problema del cambio visto en clase:


###### Algoritmo paso 1
 - Empezamos con el cambio trivial, esto es si tenemos que devolver n es suficiente una moneda de n o en terminos del ejercicio seria grabar las 30 escenas en un dia.
 
 - Para la siguiente forma de sumar n encontramos el primer elemento no uno llamamos a este p(k) (primero por la derecha) de la particion de n anterior y contamos la cantidad de unos en la variable 'unos'.
 
 - decrecemos p(k) en uno y aumentamos la variable 'unos' en uno, nos encontramos con dos casos:
     - $p(k)\geq unos$: ponemos unos en p(k+1) y p(0,1,2...k+1) es lanueva particion n.
     - $p(k)<unos$: pasamos al siguiente paso.
 - copiamos p(k) en la siguiente posición e incrementamos k, reducimos la cantidad de'unos' en p(k) y repetimos proceso hasta que unos<p(k), una vez se cumpla esa condicion colocamos unos al final de la lista, esa es nuesta siguiente partición de n.

 - El proceso acaba cuando todos los elemento son unos, en nuestro caso 30 unos
 
 - para tener en cuenta la ligaduras en las proximas secciones añadimos un parametro por el cual se seleccionan solo las formas de sumar n que no contengan numeros mayores que cierto elemento  la partición al conjunto de particiones aceptable solo si la partición no contiene elementos mayores al numero maximo de escenas por día.

In [2]:

def horarios(n,maximo=0):
    
    if maximo==0: # si no se especifica lo contrario no hay numero maximo de escenas por dia.
        maximo=n
        
    horarios = list() #lista de horarios.
    
    p = [0] * n # lista donde trabajaremos.   
    k = 0 # primer horario el elemento no nulo es el primero
    p[k] = n # el elemento no nulo es n 

    
    while True: 
        
        # añadimos horario solo si se cumplen las ligaduras
        if all([x<=maximo for x in p]):
            horarios.append(p[:k+1])
                
          # Generamos proximo horario
        unos = 0 # cantidad de dias con una escena unos
        while k >= 0 and p[k] == 1: 
            unos += p[k]  # encuentra primer dia con mas de una escena
            k -= 1        #aumenta unos  y cambia indice.
  
        # si todos los dias con una escena es el ultimo horario.
        if k < 0: 
            return horarios
        
        # le resta uno a particion anterior  
        # le suma uno a la cantidad de unos
        p[k] -= 1
        unos += 1
        #si la cantidad de unos es mayor que p[k]
        #dividimos la cantidad de unos en bloques de tamaño p[k] 
        while unos > p[k]: 
            p[k + 1] = p[k] 
            unos = unos - p[k] 
            k += 1
        # unos sobrantes en la la siguiente posición.        
        p[k + 1] = unos 
        k += 1

#ejemplo sin ligaduras.
p=horarios(3)
print('Ejemplo sin ligaduras, 6 escenas')
for i in p:
    print(i)

#ejemplo con ligaduras.
print('Ejemplo con ligaduras, 6 escenas y maximo 3 por dia')
p=horarios(6,3)

for i in p:
    print(i)



Ejemplo sin ligaduras, 6 escenas
[3]
[2, 1]
[1, 1, 1]
Ejemplo con ligaduras, 6 escenas y maximo 3 por dia
[3, 3]
[3, 2, 1]
[3, 1, 1, 1]
[2, 2, 2]
[2, 2, 1, 1]
[2, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1]


In [3]:
print(len(horarios(30,6)))

1206


2. Una vez tenemos los posibles horarios (formas de distribuir las escenas en los diferentes dias), vemos como se pueden ordenar las escenas en ese horario.
Para ello vemos que si estamos por ejemplo ( con 3 escenas) en el horario con dias $(2,1)$ las formas de ordenar las escenas en esos dias seran los numeros combinatorios. Para nuestro ejemplo seria:

$$(2,1)=\binom{3}{2}\binom{1}{1}==\binom{3}{2,1}\frac{3!}{2!1!}=3$$

3. Por ultimo no podemos olvidar que si contamos las escenas de esta forma los dias son distinguibles por el numero de escenas que contienen el dia, pero indistinguibles si los dias contienen el mismo numero de escenas. si no tubiesemos en cuenta esto las formas de distribuir 3 escenas en 3 dia de 1 escena cada dia, seria $\binom{3}{1,1,1}=6$ cuando en realidad solo hay una unica forma. Para tener este factor presente solo tenemos que dividir por la cantidad de formas de ordenar  m dias iguales esto es 3! en nuesto caso.

$$(1,1,1)=\frac{\binom{3}{1,1,1}}{3!}=\frac{3!}{1!1!1!}\frac{1}{3!}$$

4. Sumar todos los horarios.

$$N_{soluciones}=\frac{\binom{3}{3}}{1!}+\frac{\binom{3}{1,2}}{1!1!}+\frac{\binom{3}{1,1,1}}{3!}=5$$





In [4]:
from itertools import groupby
from numpy import prod
import  math 
from scipy.special import binom

def multinomial(lst):
    #calcula los coeficientes multinomiales.
    res, i = 1, sum(lst)
    i0 = lst.index(max(lst))
    for a in lst[:i0] + lst[i0+1:]:
        for j in range(1,a+1):
            res *= i
            res //= j
            i -= 1
    return res


def ordenar_escenas(horario):
    #formas de colocar escenas en un horario.
    dias_mismo_numero_escenas=list([len(list(j)) for k,j in groupby(sorted(horario))])
    
    orden_dias_escenas=list(map(lambda x:math.factorial(x),dias_mismo_numero_escenas))
    
    dias_indistinguibles= prod(orden_dias_escenas)
    
    ordenes_escenas= multinomial(horario)/dias_indistinguibles
    
    return ordenes_escenas


def contar_soluciones(escenas,maximo_dia=0):
    #suma todas las posibilidades de los diferentes horarios
    horarios_posibles=horarios(escenas,maximo_dia)
    soluciones=0 
    for horario in horarios_posibles:
        soluciones+=ordenar_escenas(horario)
    return soluciones


for i in range(1,6):   
    print(contar_soluciones(i))                            
                


1.0
2.0
5.0
15.0
52.0


Un indicio de que se trata de un resultado corrector es que esta secuencia de numeros es concida en combinatoria como numeros de Bell. que indican el numero de formas de particionar un conjunto de n elementos.

Calculamos ahora el caso de 30 escenas con y sin restricciones:

In [5]:
print('Hay {} formas de organizar 30 escenas sin limite de escenas por día'.format(contar_soluciones(30)))

Hay 8.450859747066342e+23 formas de organizar 30 escenas sin limite de escenas por día


In [6]:
print('Hay {} formas de organizar 30 escenas sin poner mas de 6 por día '.format(contar_soluciones(30,6)))

Hay 7.247301838530936e+23 formas de organizar 30 escenas sin poner mas de 6 por día 


Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)


La mejor estructura de datos para el problema clarameten son las estructuras de conjuntos disjuntos, ademas como hemos dicho antes pude haber elementos repetidos por lo tanto se trata de una estrucutra conocida en combinatoria como multiconjunto, necesitamos las particiones de un multiconjunto.

Para trabajar con estas estructuras de datos usaremos el paquete de python sympy, en particular la función del  modulo 'utilities.iterables' llamada 'multiset_partitions', esta nos proporciona las particiones de un multiconjunto teniendo encuenta todas las simetrias del problema.

Ponemos un ejemplo:

In [7]:
from sympy.utilities.iterables import multiset_partitions

print([i for i in multiset_partitions([1,1,2])])


[[[1, 1, 2]], [[1, 1], [2]], [[1, 2], [1]], [[1], [1], [2]]]


Como vemos devuelve las particiones del conjunto teniendo en cuenta que hay elementos repetidos.
Para nuestro proposito solo nos interesan las particiones que no contienen subconjuntos de mas de 6 elementos, es decir que tenemos que filtrar las particiones dadas por la función multiset_partitions y coger solo la que contengan subconjuntos de 6 o menos elementos.

Respuesta

Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?

Dado un dia del horario cogemos las escenas correspondientes a tal dia, por ejemplo si tenemos en un dia las escenas 1 y 2, tenemos la matriz:
$$
\begin{pmatrix}
1 &  1& 1 & 1 & 1 & 0 & 0 &  0& 0 & 0\\ 
0 & 0 & 1 &  1& 1 & 0 &0  &0  & 0 & 0
\end{pmatrix}
$$

La sumamos por columnas, teniendo :

$$\begin{pmatrix}
1 & 1 & 2 & 2 & 2 & 0 & 0 & 0 & 0 & 
\end{pmatrix}$$

Por ultimo contamos los elementos no nulos, ese numero es la cantidad de actores necesarios en ese dia, el coste total de un reparto de las escenas en una particion sera la suma del coste de cada dia.

Elegimos esta función objetivo debido a que todos los actores cobran lo mismo y el coste de un horario puede ser determinado solo por la presencia o no de un actor en un dia.


(*)¿Es un problema de maximización o minimización?

Claramente si queremos gastar lo menos posible, se trata de un problema de minimizar la función objetivo lo que en nuestro problema significa llamar a los actores el minimo numero de dias posibles.

Respuesta

In [9]:
def funcion_coste(calendario,escenas):
    coste=0
    for dia in calendario:
        actores_dias=np.sum(escenas[dia,:],axis=0)
        actores_dias=len(np.nonzero(actores_dias)[0])
        coste+=actores_dias 
    return coste


#cogemos una porcion del problema para probar la función coste.

subconjunto_doblaje=doblaje[:3]
print(subconjunto_doblaje,'\n')

for i in multiset_partitions(list(range(3))):
    print(i)
    print(funcion_coste(i,subconjunto_doblaje))


[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 1. 0. 0. 0.]] 

[[0, 1, 2]]
6
[[0, 1], [2]]
8
[[0, 2], [1]]
9
[[0], [1, 2]]
10
[[0], [1], [2]]
11


Como vemos funciona correctamente.

Diseña un algoritmo para resolver el problema por fuerza bruta

Respuesta:

El Algoritmo es simple, iteramos en cada salida de la función multiset_partition, comprobamos si algun dia contiene mas de 6 escenas, es decir si algun subconjunto tiene mas de 6 elementos, si cumple con nuestas restricciones calculamos la función coste, si mejora nuestro mejor resultado actualizamos.

In [25]:
def optimizar_fuerza_bruta(escenas,max_dia):
    coste_minimo=1e100 # siempre hay una mejor solucion a este numero.
    mejor_calendario=0 #reparto de las escenas.
    #Escenas unicas, 
    escenas_sin_repeticion,indices_no_repetidas,multiplicidad =np.unique(doblaje,
                                                                         return_index=True,
                                                                         return_counts=True,
                                                                         axis=0)
    #conjunto de indices.
    multiset=[[i[0]]*i[1] for i in zip(indices_no_repetidas,multiplicidad)]
    
    multiset=sum(multiset,[])
    for i in range(5,30):
        for calendario in multiset_partitions(multiset,i):
            if all(list(map(lambda x: len(x)<=max_dia,calendario))): # todos los dias menos de 6 escenas 
                coste_calendario=funcion_coste(calendario,escenas_sin_repeticion)
                if coste_calendario<coste_minimo:# si mejora nuestro mejor dia, actualizamos.
                    coste_minimo=coste_calendario
                    mejor_calendario=calendario
                    print('calendario \n ', mejor_calendario,
                          ' \n con coste \n',mejor_coste)
    return mejor_calendario,coste_minimo #devuelve mejor dia y su coste
            
        
#probamos para nuestro problema.        
optimizar_fuerza_bruta(doblaje,6)

KeyboardInterrupt: 

Calcula la complejidad del algoritmo por fuerza bruta

Respuesta

Empezamos con el problema sin restricciones, como hemos mencionado antes el temaño del problema sin  restricciones venia dado por los numeros de Bell, que representaban el numero de particiones de un conjunto en subconjuntos no vacios.  Para estos nuemeros existe una relación de recurrencia que viene dado por:

$$BELL(n)=\sum^{n-1}_{k=0}\binom{n-1}{k}BELL(k)$$

Podemos probar por indicción que: $BELL(n)\leq n^n$ 
- Hiptesis: BELL(k)$\leq k^k$ para cada k $\leq$ n-1 
- Se cumple en el caso trivial.

Si partimos de BELL(n):

$$BELL(n+1)=\sum^{n}_{k=0}\binom{n}{k}BELL(k)=\sum^{n}_{k=0}\frac{n}{n-k}\binom{n-1}{k}BELL(k)$$

$$\leq n \sum^{n-1}_{k=0}\binom{n-1}{k}k^k\leq n \sum^{n-1}_{k=0}\binom{n-1}{k}(n-1)^k=n n^{n-1}=n^n$$


Por tanto para el problema sin restricciones una cota superior es la de $n^n$, Por otro lado para una cota inferior, tenemos que si tomamos la relacion de recurrencia anterior y nos quedamos solo con el termino para k=n-2, tenemos que $BELL(n)\geq  (n-1)BELL(n-2)$, si partimos de un numero desde un n impar podemos afirmar sin perder generalidad que:

$$BELL(2n+1)\geq (2n)BELL(2(n-1))\geq (2n)(2(n-1))BELL(2(n-2))....\geq 2^nn!BELL(1)=2^nn!$$


Por tanto el crecimiento asintotico en complejidad del algoritmo podemos afirmar que se encuentra entre:
- Liminte superior: $\Theta(n^n)$
- Liminte inferior: $\Omega(2^nn!)$


Como cabe esperar cuando le añadimos las restricciones al sistema los casos validos disminuyen, pero dado que el programa por fuerza bruta  genera todas las particiones del multiconjunto esta parte tardara lo mismo con restricciones que sin ellas.

Por otra parte puede demostrarse que si incluimos las ligaduras la complejidad del problema puede verse disminuida aproximadamente en un factor $n^k$ donde k indica el numero maximo de escenas por dia. Dada la complejidad factorial y exponenecial con la que trabajamos una disminucion en la complejidad del orden de $n^k$ puede ser despreciada en la mayoria de los casos.


(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta.

Respuesta

Para mejorar el algoritmo con fuerza primero dividimos el espacio de soluciones, segun las particiones, para calcular una cota superior y una cota inferior, usamos una aproximación optimista para la cota superior y un algoritmo usando el metrodo codicioso para la cota superior de cada partición, asi podemos podar estas particiones buscando solo en aquellas en las que es posible que este la solución, en nuestro caso inicialmente tenemos unas 1200 particiones para las 30 escenas nos quedamos con solo unas 300.

Una vez con las partes del espacio de soluciones que pueden tener una solución optima al problema, buscamos empezando por los horarios mas prometedores, en nuestro caso evidentemente es el de la partición (6,6,6,6,6).



In [11]:
import numpy as np

def cota_inferior_particion(particion,escenas):
    #en cada dia metemos las escenas mas costosas.
    #Y suponemos que el coste del dia es el de la escena mas cara del dia.
    costes=np.sort(np.sum(escenas,axis=1))
    coste_minimo_estimado=0
    for i in particion:
        coste_dia=costes[-1]
        costes=np.delete(costes,np.s_[-i:])
        coste_minimo_estimado+=coste_dia
    return coste_minimo_estimado

def primera_escena(escenas_disponibles):
    #escogemos como primera escena la que mas actores involucre
    actores_en_escena=np.sum(escenas_disponibles,axis=1)
    prometedoras=np.where(actores_en_escena==actores_en_escena.max())[0]
    return prometedoras[0]


def siguiente_escena(escenas_posibles,actores_presentes):
    #devuelve la mejor escena para continuar el dia.
    #buscamos la que menos aumenta el coste
    actores_no_presentes = np.logical_not(actores_presentes)
    aumento_coste = np.sum(escenas_posibles[ :,actores_no_presentes],axis=1)
    escenas_prometedoras=np.where(aumento_coste==aumento_coste.min())
    #de entre las que menos aumentan el coste escogemos las que mas actores utilizan.
    actores_utilizados=np.sum(escenas_posibles[escenas_prometedoras],axis=1)
    escenas_prometedoras=escenas_prometedoras[0][np.where(actores_utilizados==actores_utilizados.max())]
    return escenas_prometedoras[0]


def cota_superior_particion(particion,escenas):
    #calcula la mejor solucion usando el metodo codicioso.
    horario_cota_superior=list()
    escenas_disponibles=list(range(escenas.shape[0]))
    
    for dia in particion:
        #empieza con la mejor escena encontrada
        escenas_dia=list()
        escena_elegida=escenas_disponibles[primera_escena(escenas[escenas_disponibles])]
        escenas_dia.append(escena_elegida)
        actores_presentes=escenas[escena_elegida]
        escenas_disponibles.remove(escena_elegida)
        for i in range(dia-1):
            #va rellenando con las escenas que mejor encajan.
            escena_elegida=escenas_disponibles[siguiente_escena(escenas[escenas_disponibles],actores_presentes)]
            escenas_dia.append(escena_elegida)
            actores_presentes=np.logical_or(actores_presentes,escenas[escena_elegida])
            escenas_disponibles.remove(escena_elegida)  
        horario_cota_superior.append(escenas_dia)
    return horario_cota_superior,funcion_coste(horario_cota_superior,escenas)
               

def calendario_optimo(escenas,max_dia):
 
    particiones_vivas=horarios(escenas.shape[0],max_dia)
    cotas_inferiores=[cota_inferior_particion(i,escenas) for i in particiones_vivas]
    cotas_superiores=[cota_superior_particion(i,escenas) for i in particiones_vivas]
    menor_cota_superior=sorted(cotas_superiores)[0]
    
    supervivientes=list()
    for i in range(len(cotas_inferiores)):
         if cotas_inferiores[i]<menor_cota_superior:
            supervivientes.append(particiones_vivas[i])
    particiones_vivas=supervivientes.copy()
    del supervivientes
    
    return pariciones_vivas

La función calendario optimo nos da las unicas particiones en las cules puede estar la solución al problema mejorando al algoritmo de fuerza bruta. Solo con este procedimiento sin una busqueda exaustiva podemos ver soluciones muy buenas  como es el calendario:


In [12]:
print('calendario \n ', cota_superior_particion([6,6,6,6,6],doblaje)[0],' \n con coste \n',cota_superior_particion([6,6,6,6,6],doblaje)[1])


calendario 
  [[0, 5, 6, 19, 21, 1], [10, 16, 18, 22, 3, 2], [11, 7, 8, 13, 17, 23], [9, 14, 28, 25, 12, 26], [24, 15, 27, 29, 4, 20]]  
 con coste 
 30


(*)Calcula la complejidad del algoritmo 

Respuesta:



Para el caso de un algoritmo de ramificación y poda es extremadamente dificil dar un calculo de la complejidad del algoritmo solo podemos afirmar que en la mayoria de los casos mejorara la complejidad del algoritmo por fuerza bruta, y en el peor de los casos podria igualar la complejidad del algoritmo por fuerza bruta.

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Respuesta:

Un conjunto de datos aleatorio sera cualquier matriz de ceros y unos, con numero de filas igual al numero de escenas y numero de columnas igual al numero de actores.

In [13]:
import numpy as np

def generar_datos(escenas,actores):
    datos=np.random.choice([0, 1], size=(escenas,actores))
    return datos

generar_datos(30,10)

array([[0, 1, 0, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 0, 1, 1, 0],
       [1, 0, 1, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 0, 1, 1, 1, 0],
       [1, 1, 1, 1, 0, 1, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 1, 1, 1, 1],
       [0, 0, 1, 0, 0, 0, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 1, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 0, 1, 1, 1, 1],
       [1, 0, 0, 1, 1, 1,

Respuesta

Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño


Es evidente que se puede seguir avanzando, cada partición puede ir generandose poco a poco y expandir el espacio de soluciones de  forma progresiva aplicando otra nuevamente un proceso de ramificacion y poda dando asi una solución exacta al problema y no conformandonos con una aproximada, esto no se ha hecho aqui por falta de tiempo siendo sencilla su implementación con las rutinas ya  implementadas.
